manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: apostrophes
      url-base: https://github.com/apostrophes
  projects:
    - name: zmk
      remote: apostrophes
      revision: core/hid-nkro-configurable-support
      import: app/west.yml
  self:
    path: config